5.22.release update
vertigis/vertigis-mobile-samples pull request #1
Opened 2023-02-14 22:00 UTC by jsiemensLatitudegeo

2023-02-15 00:54 UTC, kewalker approved these changes

2023-02-27 18:06 UTC, Felicity-R requested changes

2023-02-27 18:06 UTC, Felicity-R commented on Geocortex.Mobile.Samples/Geocortex.Mobile.Samples.Android/VertiGIS.Mobile.Samples.Android.csproj
> +      <Version>5.22.0-PullRequest8051.416</Version>
5.22.0.454?

2023-02-27 19:17 UTC, jsiemensLatitudegeo commented on Geocortex.Mobile.Samples/Geocortex.Mobile.Samples.Android/VertiGIS.Mobile.Samples.Android.csproj
> +      <Version>5.22.0-PullRequest8051.416</Version>
Fixed.

2023-02-27 19:55 UTC, Felicity-R approved these changes

2023-02-27 20:13 UTC, merged